[2025-07-09T06:34:24.076+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T06:34:24.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_airflare_data.extract manual__2025-07-09T06:34:22.645841+00:00 map_index=0 [queued]>
[2025-07-09T06:34:24.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_airflare_data.extract manual__2025-07-09T06:34:22.645841+00:00 map_index=0 [queued]>
[2025-07-09T06:34:24.103+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-09T06:34:24.114+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): extract> on 2025-07-09 06:34:22.645841+00:00
[2025-07-09T06:34:24.125+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5684) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-09T06:34:24.126+0000] {standard_task_runner.py:63} INFO - Started process 5688 to run task
[2025-07-09T06:34:24.127+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_airflare_data', 'extract', 'manual__2025-07-09T06:34:22.645841+00:00', '--job-id', '517', '--raw', '--subdir', 'DAGS_FOLDER/Untitled-1.py', '--cfg-path', '/tmp/tmpkvwjg8f5', '--map-index', '0']
[2025-07-09T06:34:24.128+0000] {standard_task_runner.py:91} INFO - Job 517: Subtask extract
[2025-07-09T06:34:24.183+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_airflare_data.extract manual__2025-07-09T06:34:22.645841+00:00 map_index=0 [running]> on host e6a32b72ede0
[2025-07-09T06:34:24.270+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_airflare_data' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T06:34:22.645841+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T06:34:22.645841+00:00'
[2025-07-09T06:34:24.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T06:34:24.273+0000] {Untitled-1.py:111} INFO - Начало извлечения данных для направления IKT-HKT
[2025-07-09T06:34:25.403+0000] {Untitled-1.py:26} INFO - Создание подключения к S3
[2025-07-09T06:34:25.403+0000] {Untitled-1.py:31} INFO - Подключение установлено
[2025-07-09T06:34:25.413+0000] {base.py:84} INFO - Using connection ID 'minio' for task execution.
[2025-07-09T06:34:25.413+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio', conn_type='aws') credentials retrieved from login and password.
[2025-07-09T06:34:25.745+0000] {Untitled-1.py:37} INFO - Загрузка данных в S3
[2025-07-09T06:34:25.745+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T06:34:25.746+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Untitled-1.py", line 121, in extract
    path = upload_to_s3(data=response.json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Untitled-1.py", line 41, in upload_to_s3
    hook.load_string(  # Загружает строку в S3
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1136, in load_string
    bytes_data = string_data.encode(encoding)
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'encode'
[2025-07-09T06:34:25.756+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_airflare_data, task_id=extract, run_id=manual__2025-07-09T06:34:22.645841+00:00, map_index=0, execution_date=20250709T063422, start_date=20250709T063424, end_date=20250709T063425
[2025-07-09T06:34:25.767+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 517 for task extract ('dict' object has no attribute 'encode'; 5688)
[2025-07-09T06:34:25.825+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-09T06:34:25.853+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T06:34:25.855+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
