[2025-07-07T05:39:25.874+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T05:39:25.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_airflare_data.extract manual__2025-07-07T05:39:23.316309+00:00 [queued]>
[2025-07-07T05:39:25.895+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_airflare_data.extract manual__2025-07-07T05:39:23.316309+00:00 [queued]>
[2025-07-07T05:39:25.895+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-07T05:39:25.905+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-07 05:39:23.316309+00:00
[2025-07-07T05:39:25.913+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=148) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-07T05:39:25.915+0000] {standard_task_runner.py:63} INFO - Started process 152 to run task
[2025-07-07T05:39:25.915+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_airflare_data', 'extract', 'manual__2025-07-07T05:39:23.316309+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/airflare_dag.py', '--cfg-path', '/tmp/tmp6fj55vh0']
[2025-07-07T05:39:25.917+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask extract
[2025-07-07T05:39:25.974+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_airflare_data.extract manual__2025-07-07T05:39:23.316309+00:00 [running]> on host 8eb563cea954
[2025-07-07T05:39:26.042+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_airflare_data' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T05:39:23.316309+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T05:39:23.316309+00:00'
[2025-07-07T05:39:26.043+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T05:39:27.086+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T05:39:27.087+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflare_dag.py", line 29, in extract
    df.to_json(path)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 2629, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 212, in to_json
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'D:/project/simple_airfare/simple_airfare/temp'
[2025-07-07T05:39:27.098+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_airflare_data, task_id=extract, run_id=manual__2025-07-07T05:39:23.316309+00:00, execution_date=20250707T053923, start_date=20250707T053925, end_date=20250707T053927
[2025-07-07T05:39:27.109+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task extract (Cannot save file into a non-existent directory: 'D:/project/simple_airfare/simple_airfare/temp'; 152)
[2025-07-07T05:39:27.131+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T05:39:27.151+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T05:39:27.152+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
