[2025-07-07T07:44:39.171+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T07:44:39.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_airflare_data_test.extract manual__2025-07-07T07:44:38.017327+00:00 [queued]>
[2025-07-07T07:44:39.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_airflare_data_test.extract manual__2025-07-07T07:44:38.017327+00:00 [queued]>
[2025-07-07T07:44:39.192+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-07T07:44:39.203+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-07 07:44:38.017327+00:00
[2025-07-07T07:44:39.212+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-07T07:44:39.214+0000] {standard_task_runner.py:63} INFO - Started process 256 to run task
[2025-07-07T07:44:39.213+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_airflare_data_test', 'extract', 'manual__2025-07-07T07:44:38.017327+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/Untitled-1.py', '--cfg-path', '/tmp/tmp5az_t60q']
[2025-07-07T07:44:39.215+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask extract
[2025-07-07T07:44:39.265+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_airflare_data_test.extract manual__2025-07-07T07:44:38.017327+00:00 [running]> on host e6a32b72ede0
[2025-07-07T07:44:39.337+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_airflare_data_test' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T07:44:38.017327+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T07:44:38.017327+00:00'
[2025-07-07T07:44:39.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T07:44:39.353+0000] {Untitled-1.py:59} INFO - Начало извлечения данных
[2025-07-07T07:44:40.866+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T07:44:40.867+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Untitled-1.py", line 67, in extract
    a = upload_to_s3(response.json(), key='response.json')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: upload_to_s3() got an unexpected keyword argument 'key'
[2025-07-07T07:44:40.878+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_airflare_data_test, task_id=extract, run_id=manual__2025-07-07T07:44:38.017327+00:00, execution_date=20250707T074438, start_date=20250707T074439, end_date=20250707T074440
[2025-07-07T07:44:40.888+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 62 for task extract (upload_to_s3() got an unexpected keyword argument 'key'; 256)
[2025-07-07T07:44:40.913+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T07:44:40.932+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T07:44:40.933+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
