[2025-07-07T08:46:41.305+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T08:46:41.319+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_airflare_data.load manual__2025-07-07T08:45:32.815775+00:00 [queued]>
[2025-07-07T08:46:41.324+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_airflare_data.load manual__2025-07-07T08:45:32.815775+00:00 [queued]>
[2025-07-07T08:46:41.324+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-07-07T08:46:41.333+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2025-07-07 08:45:32.815775+00:00
[2025-07-07T08:46:41.341+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=321) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-07T08:46:41.342+0000] {standard_task_runner.py:63} INFO - Started process 323 to run task
[2025-07-07T08:46:41.342+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_airflare_data', 'load', 'manual__2025-07-07T08:45:32.815775+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/Untitled-1.py', '--cfg-path', '/tmp/tmpll_e3l6n']
[2025-07-07T08:46:41.345+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask load
[2025-07-07T08:46:41.395+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_airflare_data.load manual__2025-07-07T08:45:32.815775+00:00 [running]> on host e6a32b72ede0
[2025-07-07T08:46:41.466+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_airflare_data' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T08:45:32.815775+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T08:45:32.815775+00:00'
[2025-07-07T08:46:41.467+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T08:46:41.478+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T08:46:41.479+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Untitled-1.py", line 120, in load
    df = pd.DataFrame(context.xcom_pull(key='path'))
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'xcom_pull'
[2025-07-07T08:46:41.492+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_airflare_data, task_id=load, run_id=manual__2025-07-07T08:45:32.815775+00:00, execution_date=20250707T084532, start_date=20250707T084641, end_date=20250707T084641
[2025-07-07T08:46:41.503+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 121 for task load ('dict' object has no attribute 'xcom_pull'; 323)
[2025-07-07T08:46:41.556+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T08:46:41.572+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T08:46:41.574+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
