[2025-07-09T04:03:11.549+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T04:03:11.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_airflare_data.extract manual__2025-07-09T04:03:09.687432+00:00 map_index=1 [queued]>
[2025-07-09T04:03:11.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_airflare_data.extract manual__2025-07-09T04:03:09.687432+00:00 map_index=1 [queued]>
[2025-07-09T04:03:11.570+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-09T04:03:11.580+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): extract> on 2025-07-09 04:03:09.687432+00:00
[2025-07-09T04:03:11.588+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2751) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-09T04:03:11.590+0000] {standard_task_runner.py:63} INFO - Started process 2755 to run task
[2025-07-09T04:03:11.590+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_airflare_data', 'extract', 'manual__2025-07-09T04:03:09.687432+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/Untitled-1.py', '--cfg-path', '/tmp/tmpjfdnseu0', '--map-index', '1']
[2025-07-09T04:03:11.591+0000] {standard_task_runner.py:91} INFO - Job 242: Subtask extract
[2025-07-09T04:03:11.642+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_airflare_data.extract manual__2025-07-09T04:03:09.687432+00:00 map_index=1 [running]> on host e6a32b72ede0
[2025-07-09T04:03:11.723+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_airflare_data' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T04:03:09.687432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T04:03:09.687432+00:00'
[2025-07-09T04:03:11.725+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T04:03:11.726+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T04:03:11.726+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Untitled-1.py", line 91, in extract
    origin = rout['origin']  # Место вылета
             ~~~~^^^^^^^^^^
KeyError: 'origin'
[2025-07-09T04:03:11.737+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_airflare_data, task_id=extract, run_id=manual__2025-07-09T04:03:09.687432+00:00, map_index=1, execution_date=20250709T040309, start_date=20250709T040311, end_date=20250709T040311
[2025-07-09T04:03:11.748+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 242 for task extract ('origin'; 2755)
[2025-07-09T04:03:11.764+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-09T04:03:11.773+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
