[2025-07-07T08:37:28.072+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T08:37:28.085+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_airflare_data.transform manual__2025-07-07T08:35:20.754654+00:00 [queued]>
[2025-07-07T08:37:28.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_airflare_data.transform manual__2025-07-07T08:35:20.754654+00:00 [queued]>
[2025-07-07T08:37:28.090+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-07-07T08:37:28.100+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-07-07 08:35:20.754654+00:00
[2025-07-07T08:37:28.108+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=167) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-07T08:37:28.110+0000] {standard_task_runner.py:63} INFO - Started process 169 to run task
[2025-07-07T08:37:28.109+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_airflare_data', 'transform', 'manual__2025-07-07T08:35:20.754654+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/Untitled-1.py', '--cfg-path', '/tmp/tmpetuggyyj']
[2025-07-07T08:37:28.112+0000] {standard_task_runner.py:91} INFO - Job 112: Subtask transform
[2025-07-07T08:37:28.163+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_airflare_data.transform manual__2025-07-07T08:35:20.754654+00:00 [running]> on host e6a32b72ede0
[2025-07-07T08:37:28.233+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_airflare_data' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T08:35:20.754654+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T08:35:20.754654+00:00'
[2025-07-07T08:37:28.234+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T08:37:28.254+0000] {Untitled-1.py:96} INFO - данные приняты из Xcom, начат процесс очистки
[2025-07-07T08:37:28.255+0000] {Untitled-1.py:43} INFO - Создание подключения к S3
[2025-07-07T08:37:28.255+0000] {Untitled-1.py:46} INFO - Подключение установлено, загрузка данных из S3
[2025-07-07T08:37:28.263+0000] {base.py:84} INFO - Using connection ID 'minio' for task execution.
[2025-07-07T08:37:28.264+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio', conn_type='aws') credentials retrieved from login and password.
[2025-07-07T08:37:28.446+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T08:37:28.447+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Untitled-1.py", line 98, in transform
    file = load_from_s3(bucket=path['bucket'], key=path['key'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Untitled-1.py", line 50, in load_from_s3
    data = json.load(content)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'str' object has no attribute 'read'
[2025-07-07T08:37:28.457+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL_airflare_data, task_id=transform, run_id=manual__2025-07-07T08:35:20.754654+00:00, execution_date=20250707T083520, start_date=20250707T083728, end_date=20250707T083728
[2025-07-07T08:37:28.467+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 112 for task transform ('str' object has no attribute 'read'; 169)
[2025-07-07T08:37:28.485+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T08:37:28.502+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T08:37:28.505+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
